export const analyticsPage = String.raw`<!doctype html><html lang="uk"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Karpservice · Аналітика</title>
<style>*{box-sizing:border-box}body{margin:0;background:#0b1111;color:#f2f7f5;font:16px system-ui,sans-serif}main{max-width:1100px;margin:auto;padding:32px 20px}header{display:flex;align-items:center;justify-content:space-between;gap:20px}small,p{color:#a2b8ae;line-height:1.6}h1{font-size:32px;margin-bottom:8px}h2{font-size:20px}button,input,select{font:inherit;border-radius:12px;padding:13px;border:1px solid #335147;background:#15221d;color:inherit}button{background:#68e8b0;color:#082016;cursor:pointer;font-weight:650}input{width:min(100%,440px)}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:24px 0}.card{background:#15211d;border:1px solid #273d33;border-radius:18px;padding:22px}.value{font-size:38px;margin:12px 0;font-weight:700}.toolbar{display:flex;flex-wrap:wrap;gap:12px;align-items:center}.scroll{overflow:auto}table{width:100%;border-collapse:collapse;white-space:nowrap}td,th{text-align:left;padding:15px 12px;border-bottom:1px solid #283c33}th{color:#9fbaac;font-size:13px}.note{padding:16px;border-left:3px solid #68e8b0;background:#14201b}a{color:#68e8b0}#message{color:#ffcd97}.bar{height:7px;background:#65dba7;border-radius:8px;margin-top:8px;min-width:0}.hidden{display:none}@media(max-width:650px){.cards{grid-template-columns:1fr 1fr}.card{padding:15px}.value{font-size:30px}h1{font-size:26px}header{align-items:flex-start}}</style>
<main><header><div><small>KARPSERVICE / ВЛАСНИК</small><h1>Аналітика застосунку</h1></div><button id="logout" class="hidden">Вийти</button></header>
<div id="login"><p>Введіть особистий ключ доступу. Він зберігається лише в пам’яті цієї сторінки.</p><form id="auth"><input id="key" type="password" autocomplete="off" placeholder="Ключ власника" required> <button>Відкрити</button></form></div><p id="message" role="status"></p>
<section id="report" class="hidden"><div class="toolbar"><select id="days"><option value="7">7 днів</option><option value="30" selected>30 днів</option><option value="90">90 днів</option></select><button id="refresh">Оновити</button><button id="csv">Завантажити CSV</button></div>
<p id="period"></p><div id="cards" class="cards"></div><p class="note" id="tracking"></p>
<h2>По днях · Київ</h2><div class="scroll"><table><thead><tr><th>Дата</th><th>Активні акаунти</th><th>Входи Apple</th><th>Нові акаунти</th><th>Прив’язки телефону</th><th>Записи на сервіс</th></tr></thead><tbody id="rows"></tbody></table></div>
<p>Активність — успішне завантаження профілю авторизованим користувачем, максимум один акаунт на день. Це не кількість запусків застосунку. Повторний вхід Apple рахується окремо. Денні активні акаунти не підсумовуються як унікальні за період.</p>
<h2>Завантаження з App Store</h2><p>Не підключено до цієї панелі. Дивіться First-Time Downloads і Total Downloads в <a href="https://appstoreconnect.apple.com/" target="_blank" rel="noopener noreferrer">App Store Connect → Analytics → Karpservice</a>. Кількість акаунтів не дорівнює кількості завантажень.</p></section></main>
<script>
let token='',data=null,table=[];const $=id=>document.getElementById(id);const n=v=>Number(v||0).toLocaleString('uk-UA');
function clear(){token='';data=null;table=[];$('cards').replaceChildren();$('rows').replaceChildren();$('report').classList.add('hidden');$('logout').classList.add('hidden');$('login').classList.remove('hidden');$('key').value=''}
function card(label,value,detail){const el=document.createElement('div');el.className='card';for(const [tag,t,c] of [['small',label,''],['div',n(value),'value'],['small',detail,'']]){const node=document.createElement(tag);node.className=c;node.textContent=t;el.append(node)}return el}
async function load(){ $('message').textContent='Завантаження…';try{const response=await fetch('/admin/analytics/data?days='+$('days').value,{headers:{Authorization:'Bearer '+token},cache:'no-store'});const payload=await response.json();if(!response.ok){if(response.status===401)clear();throw new Error(payload.error||'Не вдалося оновити')}data=payload;const totals={};for(const r of data.daily)totals[r.event]=(totals[r.event]||0)+Number(r.total);const today=data.daily.find(r=>r.day===data.to&&r.event==='active');$('cards').replaceChildren(card('Акаунти Apple зараз',data.snapshot.accounts,'Наявні, не заблоковані'),card('Телефон підключено',data.snapshot.linked,'Серед наявних акаунтів'),card('Активні сьогодні',today?.unique_accounts,'Унікальні акаунти за день'),card('Входи Apple',totals.apple_login,'За обраний період'),card('Нові акаунти',totals.registration,'За обраний період'),card('Записи на сервіс',totals.booking,'Успішно створені та перевірені'));
$('period').textContent=data.from+' — '+data.to+' · Оновлено '+new Date(data.generated_at).toLocaleString('uk-UA',{timeZone:'Europe/Kyiv'});
$('tracking').textContent='Збір подій розпочато '+new Date(data.started_at).toLocaleString('uk-UA',{timeZone:'Europe/Kyiv'})+'. Попередніх подій немає; за дні до початку збору — немає даних. Історія подій зберігається 93 дні.';
const first=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Kyiv',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(data.started_at));table=[];$('rows').replaceChildren();for(let offset=0;offset<data.days;offset++){const date=new Date(data.to+'T12:00:00Z');date.setUTCDate(date.getUTCDate()-offset);const day=date.toISOString().slice(0,10);const entries=data.daily.filter(r=>r.day===day);const row=[day,...['active','apple_login','registration','phone_linked','booking'].map(e=>day<first?'—':Number(entries.find(r=>r.event===e)?.[e==='active'?'unique_accounts':'total']||0))];table.push(row);const tr=document.createElement('tr');for(const v of row){const td=document.createElement('td');td.textContent=v;tr.append(td)}$('rows').append(tr)}$('login').classList.add('hidden');$('report').classList.remove('hidden');$('logout').classList.remove('hidden');$('message').textContent='';}catch(e){$('message').textContent=e.message}}
$('auth').onsubmit=e=>{e.preventDefault();token=$('key').value.trim();$('key').value='';load()};$('refresh').onclick=load;$('days').onchange=load;$('logout').onclick=clear;$('csv').onclick=()=>{if(!data)return;const lines=[['Дата','Активні акаунти','Входи Apple','Нові акаунти','Прив’язки телефону','Записи на сервіс'],...table];const url=URL.createObjectURL(new Blob(['\uFEFF'+lines.map(r=>r.join(';')).join('\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='karpservice-analytics.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
</script></html>`;
