import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { Script } from 'node:vm';
import { recordAnalytics, handleAnalytics,kyivDay } from '../src/analytics.js';
import { analyticsPage } from '../src/analytics-page.js';
function setup(){const db=new DatabaseSync(':memory:');for(const name of ['0006_apple_sign_in.sql','0008_analytics.sql'])db.exec(readFileSync(new URL('../migrations/'+name,import.meta.url),'utf8'));class St{constructor(sql,values=[]){Object.assign(this,{sql,values})}bind(...v){return new St(this.sql,v)}async run(){db.prepare(this.sql).run(...this.values);return {success:true}}async all(){return {results:db.prepare(this.sql).all(...this.values)}}}const env={AUTH_DB:{prepare:s=>new St(s),batch:async ss=>{db.exec('BEGIN');try{let result=[];for(const s of ss)result.push(/^SELECT/.test(s.sql)?await s.all():await s.run());db.exec('COMMIT');return result}catch(e){db.exec('ROLLBACK');throw e}}},SESSION_SECRET:'test-secret',ANALYTICS_ADMIN_TOKEN_SHA256:createHash('sha256').update('x'.repeat(48)).digest('hex')};return {db,env}}
test('daily activity deduplicates, logins count, identifiers rotate by day and contain no PII',async()=>{const {db,env}=setup();const date=new Date('2026-10-08T22:00:00Z');assert.equal(kyivDay(date),'2026-10-09');await recordAnalytics(env,'active','private-apple-id',{once:true,date});await recordAnalytics(env,'active','private-apple-id',{once:true,date});await recordAnalytics(env,'apple_login','private-apple-id',{date});await recordAnalytics(env,'apple_login','private-apple-id',{date});const rows=db.prepare('SELECT * FROM analytics_daily').all();assert.equal(rows.find(r=>r.event==='active').count,1);assert.equal(rows.find(r=>r.event==='apple_login').count,2);assert.equal(rows[0].day,'2026-10-09');assert.ok(rows.every(r=>/^[a-f0-9]{64}$/.test(r.actor_key)));assert.notEqual(rows[0].actor_key,rows[1].actor_key);await recordAnalytics(env,'active','private-apple-id',{once:true,date:new Date('2026-10-10T12:00:00Z')});assert.equal(db.prepare("SELECT COUNT(DISTINCT actor_key) n FROM analytics_daily WHERE event='active'").get().n,2);db.close()});
test('analytics cannot fail login when database is unavailable',async()=>{await assert.doesNotReject(recordAnalytics({AUTH_DB:{batch(){throw Error('DB down')}},SESSION_SECRET:'test'},'apple_login','id'))});
test('report fails closed, rejects query tokens and invalid dates, returns aggregate only',async()=>{const {db,env}=setup();const req=(suffix='',token)=>new Request('https://example.test/admin/analytics/data'+suffix,{headers:token?{Authorization:'Bearer '+token}:{}});assert.equal((await handleAnalytics(req(),env)).status,401);assert.equal((await handleAnalytics(req('?token='+'x'.repeat(48)),env)).status,401);assert.equal((await handleAnalytics(req('','y'.repeat(48)),env)).status,401);assert.equal((await handleAnalytics(req('?days=999','x'.repeat(48)),env)).status,400);await recordAnalytics(env,'active','secret',{once:true});const r=await handleAnalytics(req('?days=7','x'.repeat(48)),env);assert.equal(r.status,200);assert.equal(r.headers.get('Cache-Control'),'no-store');const body=await r.json();assert.equal(body.days,7);assert.equal(body.downloads,null);assert.equal(body.daily[0].unique_accounts,1);assert.ok(!JSON.stringify(body).includes('actor_key'));db.close()});
test('dashboard browser script parses and never embeds an access key',()=>{new Script(analyticsPage.match(/<script>([\s\S]*)<\/script>/)[1]);assert.ok(!analyticsPage.includes('localStorage'));assert.ok(!analyticsPage.includes('sessionStorage'))});
